{
 "title": "k6 Overview",
 "tags": [
  "collector",
  "k6",
  "loadtest",
  "prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "VUs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "expr": "k6_vus" }
   ]
  },
  {
   "title": "Requests/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(k6_http_reqs_total[1m]))"
    }
   ]
  },
  {
   "title": "Failed requests (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "avg(k6_http_req_failed_rate)" }
   ]
  },
  {
   "title": "HTTP req duration p99 (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(k6_http_req_duration_p99) * 1000"
    }
   ]
  },
  {
   "title": "HTTP req duration p99 by endpoint (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (name) (k6_http_req_duration_p99) * 1000"
    }
   ]
  },
  {
   "title": "Checks success rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "avg(k6_checks_rate)" }
   ]
  },
  {
   "title": "Iterations/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(k6_iterations_total[1m]))"
    }
   ]
  },
  {
   "title": "Data received/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(k6_data_received_total[1m]))"
    }
   ]
  }
 ]
}